### ISSUE TITLE
panic "log not found" when starting consul server

### ISSUE THREAD

**Issue by kahunacohen** [hashicorp/consul-k8s#834]
### Overview of the Issue
Error starting consul-server pod due to a panic because a log file can't be found. For several months this was working for me using the exact same steps. A few weeks ago, the consul server pod started crashing when starting up. Maybe the raft db is corrupted? If so how would restore it if I can't even get the pod up and running?

### Reproduction Steps

```
$ helm repo add hashicorp https://helm.releases.hashicorp.com
$ helm install consul hashicorp/consul --values helm-consul-values.yaml
```

helm-consul-values:

```
global:
  datacenter: vault-k8s
client:
  enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
```
    
### Logs
```
$ kubectl get pod 
NAME                     READY   STATUS             RESTARTS   AGE
consul-consul-5s57c      0/1     Running            0          14m
consul-consul-server-0   0/1     CrashLoopBackOff   7          14m
```

```
kb logs consul-consul-server-0 
==> Starting Consul agent...
           Version: '1.10.3'
           Node ID: 'd7c0b322-b792-4081-d24f-834566cf9546'
         Node name: 'consul-consul-server-0'
        Datacenter: 'vault-k8s' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 172.17.0.3 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

2021-11-03T14:38:21.369Z [WARN]  agent: BootstrapExpect is set to 1; this is the same as Bootstrap mode.
2021-11-03T14:38:21.369Z [WARN]  agent: bootstrap = true: do not enable unless necessary
2021-11-03T14:38:21.374Z [WARN]  agent.auto_config: BootstrapExpect is set to 1; this is the same as Bootstrap mode.
2021-11-03T14:38:21.374Z [WARN]  agent.auto_config: bootstrap = true: do not enable unless necessary
2021-11-03T14:38:21.473Z [INFO]  agent.server.raft: restored from snapshot: id=3-49162-1633048935993
2021-11-03T14:38:21.473Z [ERROR] agent.server.raft: failed to get log: index=49163 error="log not found"
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/raft.NewRaft(0xc000f3c640, 0x34931d0, 0xc000bf6690, 0x34b4178, 0xc000bef440, 0x34a5c50, 0xc000bfb8f0, 0x3493410, 0xc000f9d260, 0x34c30e8, ...)
        /go/pkg/mod/github.com/hashicorp/raft@v1.3.1/api.go:565 +0x14ec
github.com/hashicorp/consul/agent/consul.(*Server).setupRaft(0xc000bfc000, 0x0, 0x0)
        /home/circleci/project/consul/agent/consul/server.go:834 +0x545
github.com/hashicorp/consul/agent/consul.NewServer(0xc000f30d80, 0x34d1958, 0xc00074aab0, 0xc001052000, 0xc0009fc4d0, 0xc000dee080, 0xc000dee000, 0x3466348, 0xc0004e70e0, 0x0, ...)
        /home/circleci/project/consul/agent/consul/server.go:474 +0x1039
github.com/hashicorp/consul/agent.(*Agent).Start(0xc00027c000, 0x34a56d8, 0xc000cf2500, 0x0, 0x0)
        /home/circleci/project/consul/agent/agent.go:505 +0x7e5
github.com/hashicorp/consul/command/agent.(*cmd).run(0xc0000e4c80, 0xc00006e120, 0xe, 0xe, 0x0)
        /home/circleci/project/consul/command/agent/agent.go:243 +0xdd8
github.com/hashicorp/consul/command/agent.(*cmd).Run(0xc0000e4c80, 0xc00006e120, 0xe, 0xe, 0xc000932b00)
        /home/circleci/project/consul/command/agent/agent.go:61 +0x4d
github.com/mitchellh/cli.(*CLI).Run(0xc000226000, 0xc000abfee0, 0x80, 0xc00000c4f8)
        /go/pkg/mod/github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x41a
main.realMain(0xc0000c8058)
        /home/circleci/project/consul/main.go:53 +0x465
main.main()
        /home/circleci/project/consul/main.go:23 +0x25
```

### Expected behavior

The consul server pod starts without crashing.

### Environment details

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ helm list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
consul  default         1               2021-11-03 16:36:42.811389 +0200 EET    deployed        consul-0.36.0   1.10.3  
```

**Comment by kahunacohen** [comment]
Actually the raft db was completely removed. Is this mounted as volume that persists? I don't care about existing data, there really is none. How do I re-install consul with a new raft.db? It looks like I deleted it previously, but even when I uninstall the chart and reinstall the raft.db is gone...

**Comment by lkysow** [comment]
> Is this mounted as volume that persists?

It's mounted as a persistent volume claim.

> How do I re-install consul with a new raft.db?

Follow these uninstall directions https://www.consul.io/docs/k8s/operations/uninstall (don't miss any steps!) then re-install.

**Comment by kahunacohen** [comment]
This solved my problem, thanks!
