### ISSUE TITLE
SIGSEGV on darwin platform

### ISSUE THREAD

**Issue by nickethier** [hashicorp/consul-k8s#974]
When running the `cli` package I'm getting a seg fault from the go runtime.

Updating `golang.org/x/sys` seems to resolve the issue:
`go get -u golang.org/x/sys`

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff204a3c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff204a3c9e
stack: frame={sp:0x7ffeefbff048, fp:0x7ffeefbff098} stack=[0x7ffeefb800e8,0x7ffeefbff150)
0x00007ffeefbfef48:  0x01007ffeefbfef68  0x0000000000000004
0x00007ffeefbfef58:  0x000000000000001f  0x00007fff204a3c9e
0x00007ffeefbfef68:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbfef78:  0x0000000004038a91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff018
0x00007ffeefbfef88:  0x000000000582efec  0x00007ffeefbfefd0
0x00007ffeefbfef98:  0x0000000004038d48 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000006a5bce0
0x00007ffeefbfefa8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbfefb8:  0x00007ffeefbff018  0x0000000004038a91 <runtime.throw+0x0000000000000071>
0x00007ffeefbfefc8:  0x0000000006a5bce0  0x00007ffeefbff008
0x00007ffeefbfefd8:  0x0000000004038cd0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbfefe8
0x00007ffeefbfefe8:  0x0000000004038d00 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000006a5bce0
0x00007ffeefbfeff8:  0x0000000004038a91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff018
0x00007ffeefbff008:  0x00007ffeefbff038  0x0000000004038a91 <runtime.throw+0x0000000000000071>
0x00007ffeefbff018:  0x00007ffeefbff020  0x0000000004038ac0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff028:  0x00000000058465f0  0x000000000000002a
0x00007ffeefbff038:  0x00007ffeefbff088  0x000000000404e8d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff048: <0x00000000058465f0  0x000000c000144000
0x00007ffeefbff058:  0x00007ffeefbff0c8  0x000000000402ace6 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff068:  0x000000c000144000  0x0000000000002000
0x00007ffeefbff078:  0x000000c000000008  0x000000000407f5c0 <syscall.libc_stat64_trampoline+0x0000000000000000>
0x00007ffeefbff088:  0x00007ffeefbff0d0 !0x00007fff204a3c9e
0x00007ffeefbff098: >0x00007ffeefbff0d0  0x0000000006960000
0x00007ffeefbff0a8:  0x000000000000049b  0x00000000041061c5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff0b8:  0x000000000406c07f <runtime.syscall+0x000000000000001f>  0x000000c00009eab8
0x00007ffeefbff0c8:  0x00007ffeefbff110  0x000000c00009ea88
0x00007ffeefbff0d8:  0x0000000004069ef0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff0e8:  0x000000c000132b00  0x2b00000005972c20
0x00007ffeefbff0f8:  0x0000000000000010  0x000000000558dbc0
0x00007ffeefbff108:  0x00000000000005a0  0x000000c0000001a0
0x00007ffeefbff118:  0x0000000004068009 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff128:  0x0000000005addea8  0x0000000006a5bce0
0x00007ffeefbff138:  0x00007ffeefbff180  0x0000000004067f05 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff148:  0x0000000004067ebd <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x58465f0, 0xc000144000})
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff204a3c9e
stack: frame={sp:0x7ffeefbff048, fp:0x7ffeefbff098} stack=[0x7ffeefb800e8,0x7ffeefbff150)
0x00007ffeefbfef48:  0x01007ffeefbfef68  0x0000000000000004
0x00007ffeefbfef58:  0x000000000000001f  0x00007fff204a3c9e
0x00007ffeefbfef68:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbfef78:  0x0000000004038a91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff018
0x00007ffeefbfef88:  0x000000000582efec  0x00007ffeefbfefd0
0x00007ffeefbfef98:  0x0000000004038d48 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000006a5bce0
0x00007ffeefbfefa8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbfefb8:  0x00007ffeefbff018  0x0000000004038a91 <runtime.throw+0x0000000000000071>
0x00007ffeefbfefc8:  0x0000000006a5bce0  0x00007ffeefbff008
0x00007ffeefbfefd8:  0x0000000004038cd0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbfefe8
0x00007ffeefbfefe8:  0x0000000004038d00 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000006a5bce0
0x00007ffeefbfeff8:  0x0000000004038a91 <runtime.throw+0x0000000000000071>  0x00007ffeefbff018
0x00007ffeefbff008:  0x00007ffeefbff038  0x0000000004038a91 <runtime.throw+0x0000000000000071>
0x00007ffeefbff018:  0x00007ffeefbff020  0x0000000004038ac0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff028:  0x00000000058465f0  0x000000000000002a
0x00007ffeefbff038:  0x00007ffeefbff088  0x000000000404e8d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff048: <0x00000000058465f0  0x000000c000144000
0x00007ffeefbff058:  0x00007ffeefbff0c8  0x000000000402ace6 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff068:  0x000000c000144000  0x0000000000002000
0x00007ffeefbff078:  0x000000c000000008  0x000000000407f5c0 <syscall.libc_stat64_trampoline+0x0000000000000000>
0x00007ffeefbff088:  0x00007ffeefbff0d0 !0x00007fff204a3c9e
0x00007ffeefbff098: >0x00007ffeefbff0d0  0x0000000006960000
0x00007ffeefbff0a8:  0x000000000000049b  0x00000000041061c5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff0b8:  0x000000000406c07f <runtime.syscall+0x000000000000001f>  0x000000c00009eab8
0x00007ffeefbff0c8:  0x00007ffeefbff110  0x000000c00009ea88
0x00007ffeefbff0d8:  0x0000000004069ef0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff0e8:  0x000000c000132b00  0x2b00000005972c20
0x00007ffeefbff0f8:  0x0000000000000010  0x000000000558dbc0
0x00007ffeefbff108:  0x00000000000005a0  0x000000c0000001a0
0x00007ffeefbff118:  0x0000000004068009 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff128:  0x0000000005addea8  0x0000000006a5bce0
0x00007ffeefbff138:  0x00007ffeefbff180  0x0000000004067f05 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff148:  0x0000000004067ebd <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x41061c0, 0x1, 0x40487413, 0xc00009eb48)
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc00009eab8 sp=0xc00009ea98 pc=0x4066abb
syscall.syscall(0x40766e6, 0x10, 0xc00009eb70, 0x4076618)
        <autogenerated>:1 +0x26 fp=0xc00009eb00 sp=0xc00009eab8 pc=0x406c846
golang.org/x/sys/unix.ioctl(0x580634a, 0x4, 0x100c00009eb68)
        /Users/nethier/go/pkg/mod/golang.org/x/sys@v0.0.0-20210426230700-d19ff857e887/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc00009eb30 sp=0xc00009eb00 pc=0x4105d19
golang.org/x/sys/unix.IoctlGetTermios(...)
        /Users/nethier/go/pkg/mod/golang.org/x/sys@v0.0.0-20210426230700-d19ff857e887/unix/ioctl.go:73
github.com/mattn/go-isatty.IsTerminal(0x580634a)
        /Users/nethier/go/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc00009eba0 sp=0xc00009eb30 pc=0x4106290
github.com/fatih/color.init()
        /Users/nethier/go/pkg/mod/github.com/fatih/color@v1.9.0/color.go:21 +0x7a fp=0xc00009ebd8 sp=0xc00009eba0 pc=0x414669a
runtime.doInit(0x696d380)
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/proc.go:6498 +0x123 fp=0xc00009ed10 sp=0xc00009ebd8 pc=0x4048543
runtime.doInit(0x6977cc0)
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc00009ee48 sp=0xc00009ed10 pc=0x4048491
runtime.doInit(0x6972fa0)
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc00009ef80 sp=0xc00009ee48 pc=0x4048491
runtime.main()
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/proc.go:238 +0x1e6 fp=0xc00009efe0 sp=0xc00009ef80 pc=0x403b3a6
runtime.goexit()
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00009efe8 sp=0xc00009efe0 pc=0x406a1e1
exit status 2
```

**Comment by t-eckert** [comment]
@nickethier, thank you for opening this issue. @dnephin knew why this was happening and chimed in helpfully on Slack. We need to update `http://golang.org/x/sys` to fix this issue.
